exec.sh: add ldconfig
ldconfig does not have an interpreter and thus cannot be run with the
preloaded iamroot library to create links and cache:

	ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
        error: command failed to execute correctly

file reports ldconfig as a pie executable:

	/usr/bin/ldconfig: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=851609f1765d9ba3dad0edda14c6d830f71433ad, for GNU/Linux 4.4.0, stripped

Hopefully, ldconfig has support for the option -r root:

	-r root Change to and use root as the root directory.

This handles ldconfig in the script exec.sh and appends the -r
$IAMROOT_ROOT to its list of arguments.