nftw{,64}: fix maybe-uninitialized warning
Fixes:

	$ make
	(...)
	cc -g -Werror -Wno-deprecated-declarations -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=14 -DPREFIX=/usr/local  -c -o nftw.o /home/gportay/src/iamroot/nftw.c
	/home/gportay/src/iamroot/nftw.c: In function ‘do_nftw’:
	/home/gportay/src/iamroot/nftw.c:132:20: error: ‘dfd’ may be used uninitialized [-Werror=maybe-uninitialized]
	  132 |                 if (dfd < 0) {
	      |                    ^
	/home/gportay/src/iamroot/nftw.c:77:13: note: ‘dfd’ was declared here
	   77 |         int dfd;
	      |             ^~~
	/home/gportay/src/iamroot/nftw.c:133:31: error: ‘err’ may be used uninitialized [-Werror=maybe-uninitialized]
	  133 |                         errno = err;
	      |                               ^
	/home/gportay/src/iamroot/nftw.c:78:13: note: ‘err’ was declared here
	   78 |         int err;
	      |             ^~~

Note: OpenBSD 7.3 uses clang 13.0.0 and tries to ignore the GCC pragma
diagnostic and it raises the error below has it is not supported:

	bash-5.2$ make
	(...)
	cc -Werror -DNVERBOSE -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=14 -DPREFIX=/usr/local  -c -o nftw.o /home/freebox/src/iamroot/nftw.c
	/home/freebox/src/iamroot/nftw.c:39:32: error: unknown warning group '-Wmaybe-uninitialized', ignored [-Werror,-Wunknown-warning-option]
	#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
	                               ^
	1 error generated.

	$ bash-5.2$ cc --version
	OpenBSD clang version 13.0.0
	Target: aarch64-unknown-openbsd7.3
	Thread model: posix
	InstalledDir: /usr/bin