Fix "Output the returned values" once more again
NetBSD raises the error below:

Fixes:

	$ make CFLAGS+=-Werror
	(...)
	cc -Werror -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=11 -DPREFIX=/usr/local  -c -o closefrom.o closefrom.c
	In file included from closefrom.c:16:0:
	closefrom.c: In function ‘closefrom’:
	closefrom.c:107:21: error: ‘data’ undeclared (first use in this function)
	   __fpath(fd), ret, data.buf);
	                     ^
	iamroot.h:202:56: note: in definition of macro ‘__debug’
	 #define __debug(fmt, ...) __verbosef(3, __func__, fmt, __VA_ARGS__)
	                                                        ^~~~~~~~~~~
	closefrom.c:107:21: note: each undeclared identifier is reported only once for each function it appears in
	   __fpath(fd), ret, data.buf);
	                     ^
	iamroot.h:202:56: note: in definition of macro ‘__debug’
	 #define __debug(fmt, ...) __verbosef(3, __func__, fmt, __VA_ARGS__)
	                                                        ^~~~~~~~~~~
	gmake: *** [<builtin>: closefrom.o] Error 1

This fixes commit 837a1e430f13c696811d8fdf59c51bca5b83b318.