Add glibc 64 variants
Fixes:

	installing systemd...
	Failed to take /etc/passwd lock: Permission denied
	(...)
	( 3/10) Reloading system manager configuration...
	Failed to reload daemon: Transport endpoint is not connected
	error: command failed to execute correctly
	(...)
	( 6/10) Creating temporary files...
	Failed to copy files to /etc/crypttab: Permission denied
	Failed to copy files to /etc/gshadow: Permission denied
	Failed to copy files to /etc/shadow: Permission denied
	symlink(/etc/machine-id, /var/lib/dbus/machine-id) failed: No such file or directory
	Failed to open directory 'portables': Permission denied
	Failed to open directory 'machines': Permission denied
	Failed to open directory 'private': Permission denied
	Failed to open directory 'private': Permission denied
	Failed to open directory 'private': Permission denied
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal failed: Operation not permitted
	Failed to re-open '/var/log/journal': Operation not permitted
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal/403c047caf5e41c99814685d09c6bd55 failed: Operation not permitted
	Failed to re-open '/var/log/journal/403c047caf5e41c99814685d09c6bd55': Operation not permitted
	Failed to re-open '/var/log/journal/remote': Operation not permitted
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /run/log/journal failed: Operation not permitted
	Setting access ACL "u::rw-,g::r-x,g:wheel:r--,g:adm:r--,m::r--,o::---" on /var/log/journal/403c047caf5e41c99814685d09c6bd55/system.journal failed: Operation not permitted
	error: command failed to execute correctly
	(...)
	( 9/10) Rebuilding certificate stores...
	p11-kit: couldn't create file: /etc/ca-certificates/extracted/tls-ca-bundle.pem: Unknown error 13
	p11-kit: couldn't create file: /etc/ca-certificates/extracted/email-ca-bundle.pem: Unknown error 13
	p11-kit: couldn't create file: /etc/ca-certificates/extracted/objsign-ca-bundle.pem: Unknown error 13
	p11-kit: couldn't create file: /etc/ca-certificates/extracted/ca-bundle.trust.crt: Unknown error 13
	p11-kit: couldn't create file: /etc/ca-certificates/extracted/edk2-cacerts.bin: Unknown error 13
	p11-kit: couldn't create file: /etc/ssl/certs/java/cacerts: Unknown error 13
	p11-kit: couldn't create file: /etc/ca-certificates/extracted/cadir/ACCVRAIZ1.pem: Unknown error 13

Reveals:

	installing systemd...
	Initializing machine ID from random generator.
	Warning: /absolute/path/to/rootfs/etc: contains root '/absolute/path/to/rootfs'
	Failed to write /etc/machine-id: No such file or directory
	Failed to write files: Permission denied
	(...)
	( 3/10) Reloading system manager configuration...
	Failed to reload daemon: Interactive authentication required.
	error: command failed to execute correctly
	(...)
	( 6/10) Creating temporary files...
	Failed to validate path /run/systemd/ask-password: No such file or directory
	Failed to validate path /run/systemd/seats: No such file or directory
	Failed to validate path /run/systemd/sessions: No such file or directory
	Failed to validate path /run/systemd/users: No such file or directory
	Failed to validate path /run/systemd/machines: No such file or directory
	Failed to validate path /run/systemd/shutdown: No such file or directory
	Failed to validate path /run/systemd/netif: No such file or directory
	Failed to validate path /run/systemd/netif/links: No such file or directory
	Failed to validate path /run/systemd/netif/leases: No such file or directory
	Failed to validate path /run/systemd/netif/lldp: No such file or directory
	Failed to validate path /dev/snd/seq: No such file or directory
	Failed to validate path /dev/snd/timer: No such file or directory
	Failed to validate path /dev/loop-control: No such file or directory
	Failed to validate path /dev/net/tun: No such file or directory
	Failed to validate path /dev/fuse: No such file or directory
	Failed to validate path /dev/kvm: No such file or directory
	Failed to validate path /run/log/journal: No such file or directory
	Failed to validate path /run/log/journal: No such file or directory
	(...)
	( 9/10) Rebuilding certificate stores...
	p11-kit: couldn't set file permissions: /etc/ca-certificates/extracted/tls-ca-bundle.pem.XXXXXX: Unknown error 2
	p11-kit: couldn't set file permissions: /etc/ca-certificates/extracted/email-ca-bundle.pem.XXXXXX: Unknown error 2
	p11-kit: couldn't set file permissions: /etc/ca-certificates/extracted/objsign-ca-bundle.pem.XXXXXX: Unknown error 2
	p11-kit: couldn't set file permissions: /etc/ca-certificates/extracted/ca-bundle.trust.crt.XXXXXX: Unknown error 2
	p11-kit: couldn't set file permissions: /etc/ca-certificates/extracted/edk2-cacerts.bin.XXXXXX: Unknown error 2
	p11-kit: couldn't set file permissions: /etc/ssl/certs/java/cacerts.XXXXXX: Unknown error 2
	p11-kit: couldn't set file permissions: /etc/ca-certificates/extracted/cadir/ACCVRAIZ1.pem.XXXXXX: Unknown error 2