exec.sh: handle gpasswd
Fixes:

	Adding user `syslog' to group `adm' ...
	Warning: host-running /usr/bin/gpasswd -a syslog adm
	gpasswd: user 'syslog' does not exist
	adduser: `/usr/bin/gpasswd -a syslog adm' returned error code 3. Exiting.

Raises:

	Error: Command not handled: /bin/gpasswd -a syslog adm
	adduser: `/bin/gpasswd -a syslog adm' returned error code 1. Exiting.