group: fix calloc transposed arguments warning
GCC has introduces the new warning option -Wcalloc-transposed-args[1]
since version 14.

According to the online documentation[1]:

	Warn about calls to allocation functions decorated with
	attribute alloc_size with two arguments, which use sizeof
	operator as the earlier size argument and don’t use it as the
	later size argument. This is a coding style warning. The first
	argument to calloc is documented to be number of elements in
	array, while the second argument is size of each element, so
	calloc (n, sizeof (int)) is preferred over calloc (sizeof (int),
	n). If sizeof in the earlier argument and not the latter is
	intentional, the warning can be suppressed by using calloc
	(sizeof (struct S) + 0, n) or calloc (1 * sizeof (struct S), 4)
	or using sizeof in the later argument as well.

Fixes:

	cc -Werror -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=21 -DPREFIX=/usr/local  -c -o group.o /home/gportay/src/iamroot/group.c
	/home/gportay/src/iamroot/group.c: In function ‘__getgrent_a’:
	/home/gportay/src/iamroot/group.c:92:30: error: ‘calloc’ sizes specified with ‘sizeof’ in the earlier argument and not in the later argument [-Werror=calloc-transposed-args]
	   92 |         *mem = calloc(sizeof(char *), *nmem+1);
	      |                              ^~~~
	/home/gportay/src/iamroot/group.c:92:30: note: earlier argument should specify number of elements, later size of each element
	cc1: all warnings being treated as errors

[1]: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcalloc-transposed-args