ld: fix build issue on OpenBSD
This fixes commit 7243309fd1eec4c3c3f1c5172c3e7e442c8825bf.

Fixes:

	$ make
	(...)
	cc -DNVERBOSE -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=22 -DPREFIX=/usr/local  -c -o ld.o ld.c
	ld.c:56:3: warning: implicit declaration of function 'ElfW' is invalid in C99 [-Wimplicit-function-declaration]
	                ElfW(Phdr) *phdr = (ElfW(Phdr) *)(&info->dlpi_phdr[i]);
	                ^
	ld.c:56:35: error: expected expression
	                ElfW(Phdr) *phdr = (ElfW(Phdr) *)(&info->dlpi_phdr[i]);
	                                                ^
	ld.c:56:28: error: use of undeclared identifier 'Phdr'; did you mean 'chdir'?
	                ElfW(Phdr) *phdr = (ElfW(Phdr) *)(&info->dlpi_phdr[i]);
	                                         ^~~~
	                                         chdir
	/usr/include/unistd.h:327:6: note: 'chdir' declared here
	int      chdir(const char *);
	         ^
	ld.c:56:8: error: use of undeclared identifier 'Phdr'
	                ElfW(Phdr) *phdr = (ElfW(Phdr) *)(&info->dlpi_phdr[i]);
	                     ^
	ld.c:56:15: error: use of undeclared identifier 'phdr'
	                ElfW(Phdr) *phdr = (ElfW(Phdr) *)(&info->dlpi_phdr[i]);
	                            ^
	ld.c:57:32: error: expected expression
	                ElfW(Dyn) *dyn = (ElfW(Dyn) *)(info->dlpi_addr + phdr->p_vaddr);
	                                             ^
	ld.c:57:26: error: use of undeclared identifier 'Dyn'
	                ElfW(Dyn) *dyn = (ElfW(Dyn) *)(info->dlpi_addr + phdr->p_vaddr);
	                                       ^
	ld.c:57:52: error: use of undeclared identifier 'phdr'
	                ElfW(Dyn) *dyn = (ElfW(Dyn) *)(info->dlpi_addr + phdr->p_vaddr);
	                                                                 ^
	ld.c:57:8: error: use of undeclared identifier 'Dyn'
	                ElfW(Dyn) *dyn = (ElfW(Dyn) *)(info->dlpi_addr + phdr->p_vaddr);
	                     ^
	ld.c:57:14: error: use of undeclared identifier 'dyn'
	                ElfW(Dyn) *dyn = (ElfW(Dyn) *)(info->dlpi_addr + phdr->p_vaddr);
	                           ^
	ld.c:59:13: error: expected ';' after expression
	                ElfW(Addr) strtab = 0;
	                          ^
	                          ;
	ld.c:59:8: error: use of undeclared identifier 'Addr'
	                ElfW(Addr) strtab = 0;
	                     ^
	ld.c:59:14: error: use of undeclared identifier 'strtab'
	                ElfW(Addr) strtab = 0;
	                           ^
	ld.c:67:8: error: use of undeclared identifier 'dyn'
	                        if (dyn[j].d_tag != DT_STRTAB)
	                            ^
	ld.c:70:4: error: use of undeclared identifier 'strtab'
	                        strtab = dyn[j].d_un.d_ptr;
	                        ^
	ld.c:70:13: error: use of undeclared identifier 'dyn'
	                        strtab = dyn[j].d_un.d_ptr;
	                                 ^
	ld.c:75:8: error: use of undeclared identifier 'strtab'
	                if (!strtab)
	                     ^
	ld.c:80:8: error: use of undeclared identifier 'dyn'
	                        if (dyn[j].d_tag != DT_RUNPATH)
	                            ^
	ld.c:83:41: error: use of undeclared identifier 'dyn'
	                        dt_runpath = (const char *)(strtab + dyn[j].d_un.d_ptr);
	                                                             ^
	ld.c:83:32: error: use of undeclared identifier 'strtab'
	                        dt_runpath = (const char *)(strtab + dyn[j].d_un.d_ptr);
	                                                    ^
	1 warning and 19 errors generated.