Fix runtime issue with glibc 2.38
The library glibc has introduced new functions for the upcoming standard
C23[1]. These new 31 functions uses the prefix __isoc23_[2].

The library iamroot uses three functions strtol(), strtoul() and
sscanf() from the libc that are now prefixed by __iso23_. See commits
[3] and [4].

Since the original function names are macros redirecting to the new
prefixed symbols, the iamroot library needs the prefixed symbols:

	$ readelf -a x86_64/libiamroot-linux-x86-64.so.2 | grep __isoc23
	000000036020  000400000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc23_sscanf + 0
	000000036120  001500000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc23_strtol + 0
	000000036140  001800000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc23_strtoul + 0
	     4: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	    21: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	    24: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul
	   938: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	  1008: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	  1018: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul

	$ readelf -a i686/libiamroot-linux.so.2 | grep __isoc23
	0002b010  00000407 R_386_JUMP_SLOT   00000000   __isoc23_sscanf
	0002b090  00001507 R_386_JUMP_SLOT   00000000   __isoc23_strtol
	0002b0a0  00001807 R_386_JUMP_SLOT   00000000   __isoc23_strtoul
	     4: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	    21: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	    24: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul
	   942: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	  1012: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	  1022: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul

And not the original ones:

	$ readelf -a x86_64/libiamroot-linux-x86-64.so.2 | grep -E '(strtol|strtoul|sscanf)'
	000000036020  000400000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc23_sscanf + 0
	000000036120  001500000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc23_strtol + 0
	000000036140  001800000007 R_X86_64_JUMP_SLO 0000000000000000 __isoc23_strtoul + 0
	     4: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	    21: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	    24: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul
	   938: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	  1008: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	  1018: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul

	$ readelf -a i686/libiamroot-linux.so.2 | grep -E '(strtol|strtoul|sscanf)'
	0002b010  00000407 R_386_JUMP_SLOT   00000000   __isoc23_sscanf
	0002b090  00001507 R_386_JUMP_SLOT   00000000   __isoc23_strtol
	0002b0a0  00001807 R_386_JUMP_SLOT   00000000   __isoc23_strtoul
	     4: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	    21: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	    24: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul
	   942: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_sscanf
	  1012: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtol
	  1022: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND __isoc23_strtoul

This leads to the error below if chroot'ing:
 - from a glibc world compiled with the new C2x standard and glibc >= 2.38
 - to a glibc world compiled without the new C2x stanard or glibc < 2.38

	/bin/bash: symbol lookup error: /home/gportay/src/iamroot-for-int/i686/libiamroot-linux.so.2: undefined symbol: __isoc23_strtol

Therefore, the iamroot library needs a compatibility layer to chroot in
a former glibc world.

This intercepts the new introduced C2x functions and forwards them to
the next symbol if exists or to the original symbol.

Fixes:

	installing p11-kit...
	/usr/bin/bash: symbol lookup error: /home/gportay/src/iamroot/i686/libiamroot-linux.so.2: undefined symbol: __isoc23_strtol
	error: command failed to execute correctly

[1]: https://en.wikipedia.org/wiki/C23_(C_standard_revision)
[2]: https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/x86_64/64/libc.abilist;hb=glibc-2.38#l2545
[3]: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=64924422a99690d147a166b4de3103f3bf3eaf6c
[4]: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=2d88df541132f09454d947c498103aa7be76b652