chroot: fix memory areas overlaps once again
This fixes commit 922953afae60c7e5e45645a39438a5fdc728f4dc.

Fixes:

	$ make
	(...)
	cc -g -Werror -Wno-deprecated-declarations -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=14 -DPREFIX=/usr/local  -c -o chroot.o /home/gportay/src/iamroot/chroot.c
	In file included from /usr/include/string.h:548,
	                 from /home/gportay/src/iamroot/chroot.c:10:
	In function ‘strncpy’,
	    inlined from ‘__striprootdir’ at /home/gportay/src/iamroot/chroot.c:265:3:
	/usr/include/bits/string_fortified.h:95:10: error: ‘__builtin_strncpy’ accessing between 0 and 2147483647 bytes at offsets 0 and [0, 4096] may overlap up to 2147483647 bytes at offset [0, 2147483646] [-Werror=restrict]
	   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
	      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	   96 |                                   __glibc_objsize (__dest));
	      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
	cc1: all warnings being treated as errors