Add {,f}verbosef()
Note: This commit requires 72ffef61ed71a72074389024b8d7f7e01c8b6dcc that
fixes the segmentation below:

	$ iamroot-shell -c "pacstrap arch-rootfs"
	(...)
	downloading required keys...
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: keyring is not writable
	error: required key missing from keyring
	error: failed to commit transaction (unexpected error)
	Errors occurred, no packages were upgraded.
	==> ERROR: Failed to install packages to new root