tests: execveat: conditionize glibc 2.34 specific code
	VERSIONS

	execveat() was added to Linux in kernel 3.19.  Library support
	was added to glibc in version 2.34.

Fixes:

	$ cc -fPIC -Wall -Wextra -D_GNU_SOURCE -Wno-error=deprecated-declarations   execveat.c   -o test-execveat
	execveat.c: In function 'main':
	execveat.c:16:2: warning: implicit declaration of function 'execveat'; did you mean 'execve'? [-Wimplicit-function-declaration]
	   16 |  execveat(AT_FDCWD, "/bin/sh", argv, environ, AT_EMPTY_PATH);
	      |  ^~~~~~~~
	      |  execve

	$ cat /etc/os-release
	PRETTY_NAME="Debian GNU/Linux bookworm/sid"
	NAME="Debian GNU/Linux"
	ID=debian
	HOME_URL="https://www.debian.org/"
	SUPPORT_URL="https://www.debian.org/support"
	BUG_REPORT_URL="https://bugs.debian.org/"

	$ ls -l /lib/x86_64-linux-gnu/libc.so.6
	lrwxrwxrwx 1 root root 12 Feb 21 08:47 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.33.so

This makes compilation successfull against debian testing (bookworm).