tests: ish: test on FreeBSD and NetBSD
The binary bash is located in /usr/local/bin on the FreeBSD and OpenBSD
systems and in /usr/pkg/bin on NetBSD the system:

	[freebox@freebsd ~/src/iamroot]$ uname -s
	FreeBSD
	[freebox@freebsd ~/src/iamroot]$ which bash
	/usr/local/bin/bash

	-bash-5.2$ uname -s
	NetBSD
	-bash-5.2$ which bash
	/usr/pkg/bin/bash

	-bash-5.2$ uname -s
	OpenBSD
	-bash-5.2$ which bash
	/usr/local/bin/bash

Fixes:

	[freebox@freebsd ~/src/iamroot]$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --shell /bin/bash sets the shell interpretor...
	execvP: No such file or directory
	ish: test option --shell /bin/bash sets the shell interpretor: [KO]
	Test report:
	ish: test option --shell /bin/bash sets the shell interpretor at line 286 has failed!
	12 test(s) succeed!
	Error: 1 test(s) failed!
	Exited!

	-bash-5.2$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --shell /bin/bash sets the shell interpretor...
	execvpe: No such file or directory
	ish: test option --shell /bin/bash sets the shell interpretor: [KO]
	Test report:
	ish: test option --shell /bin/bash sets the shell interpretor at line 288 has failed!
	12 test(s) succeed!
	Error: 1 test(s) failed!
	Exited!

Also, the procfs(5) is mostly used on Linux system[1][2], it is unused
on the FreeBSD system[3], it is removed OpenBSD system since 5.7[4], and
it is used on NetBSD system[5][6]:

	[freebox@freebsd ~/src/iamroot]$ uname -s
	FreeBSD
	[freebox@freebsd ~/src/iamroot]$ mount | grep /proc

	-bash-5.2$ uname -s
	NetBSD
	-bash-5.2$ mount | grep /proc
	procfs on /proc type procfs (local)

	-bash-5.2$ uname -s
	OpenBSD
	-bash-5.2$ mount | grep /proc

The NetBSD's procfs(5) filesystem does not symlink the filedescriptors
to the opened file:

	-bash-5.2$ uname -s
	NetBSD
	bash-5.2$ exec 100>&2 && ls -l /proc/self/fd/100
	crw--w----  1 freebox  tty  7, 0 Oct 12 17:51 /proc/self/fd/100

Note: The FreeBSD's procfs(5) filesystem does not implement the magic
symlink /proc/self nor the list of symlinks to open files directory
/proc/<pid>/fd:

	[freebox@freebsd ~/src/iamroot]$ uname -s
	FreeBSD
	[freebox@freebsd ~/src/iamroot]$ sudo mount -t procfs none /proc
	[freebox@freebsd ~/src/iamroot]$ exec 100>&2
	[freebox@freebsd ~/src/iamroot]$ ls -l /proc/self/
	ls: /proc/self/: No such file or directory
	[freebox@freebsd ~/src/iamroot]$ ls -l /proc/$$/fd
	ls: /proc/96739/fd: No such file or directory

Fixes:

	[freebox@freebsd ~/src/iamroot]$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --debug-fd 100 sets and duplicates debug fd...
	IAMROOT_DEBUG_FD=100
	ish: test option --debug-fd 100 sets and duplicates debug fd: [KO]
	Test report:
	ish: test option --debug-fd 100 sets and duplicates debug fd at line 342 has failed!
	18 test(s) succeed!
	Error: 1 test(s) failed!
	Exited!

	[freebox@freebsd ~/src/iamroot]$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --debug-fd 100 sets and duplicates debug fd...
	IAMROOT_DEBUG_FD=100
	ish: test option --debug-fd 100 sets and duplicates debug fd: [KO]
	Test report:
	ish: test option --debug-fd 100 sets and duplicates debug fd at line 345 has failed!
	17 test(s) succeed!
	Error: 1 test(s) failed!
	Exited!

	-bash-5.2$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --debug-fd 100 sets and duplicates debug fd...
	IAMROOT_DEBUG_FD=100
	ish: test option --debug-fd 100 sets and duplicates debug fd: [KO]
	Test report:
	ish: test option --debug-fd 100 sets and duplicates debug fd at line 342 has failed!
	18 test(s) succeed!
	Error: 1 test(s) failed!
	Exited!

	-bash-5.2$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --debug-fd 100 sets and duplicates debug fd...
	IAMROOT_DEBUG_FD=100
	ish: test option --debug-fd 100 sets and duplicates debug fd: [KO]
	Test report:
	ish: test option --debug-fd 100 sets and duplicates debug fd at line 345 has failed!
	17 test(s) succeed!
	Error: 1 test(s) failed!
	Exited!

This enables testing for ish on FreeBSD and NetBSD, uses the filename of
the bash interpreter and disables tests using the procfs(5) filesystem.

Note: The binary /bin/sh is statically linked on OpenBSD (as every other
binaries in the /bin directory). As a consequence, the tests have to be
rewritten to pass successfully.

FIXME:

	-bash-5.2$ make test-ish EXIT_ON_ERROR=1
	(...)
	Running ish: test option --shell /bin/sh sets the shell interpretor...
	Warning: running /bin/sh -c env
	SHELL=/bin/sh
	ish: test option --shell /bin/sh sets the shell interpretor: [OK]
	(...)
	Test report:
	22 test(s) succeed!

[1]: https://www.kernel.org/doc/html/latest/_sources/filesystems/proc.rst.txt
[2]: https://linux.die.net/man/5/proc
[3]: https://man.freebsd.org/cgi/man.cgi?query=procfs
[4]: https://www.openbsd.org/57.html
[4]: https://man.netbsd.org/mount_procfs.8
[5]: https://man.netbsd.org/fd.4