dso: define macro ELFOSABI_GNU for OpenBSD
OpenBSD does not define the macro ELFOSABI_GNU; only the former
compatibility alias macro ELFOSABI_LINUX is defined.

From /usr/include/elf.h on GNU/Linux:

	#define ELFOSABI_GNU            3       /* Object uses GNU ELF extensions.  */
	#define ELFOSABI_LINUX          ELFOSABI_GNU /* Compatibility alias.  */

Fixes:

	dso.c:992:45: error: use of undeclared identifier 'ELFOSABI_GNU'
	        return ehdr && (ehdr->e_ident[EI_OSABI] == ELFOSABI_GNU);
	                                                   ^

This commit fixes 5939092ca6bad08e2b6feb5defae009441f4a90a.