linux.mk: alpine: update mirror and fix 3.16
Backported from[1].

The package musl-utils-1.2.3-r0.apk[2] depends on scanelf which depends
on scanelf that is missing from[3].

	C:Q1VVfxM3uSO0X38HWpj1LN0E61fxo=
	P:musl-utils
	V:1.2.3-r0
	A:x86_64
	S:36938
	I:135168
	T:the musl c library (libc) implementation
	U:https://musl.libc.org/
	L:MIT BSD GPL2+
	o:musl
	m:Timo Teräs <timo.teras@iki.fi>
	t:1649396308
	c:ee13d43a53938d8a04ba787b9423f3270a3c14a7
	D:scanelf so:libc.musl-x86_64.so.1
	p:cmd:getconf=1.2.3-r0 cmd:getent=1.2.3-r0 cmd:iconv=1.2.3-r0 cmd:ldconfig=1.2.3-r0 cmd:ldd=1.2.3-r0

The packages musl-utils-1.2.3-r0.apk[4] and scanelf-1.3.4-r0.apk[5] are
present in[5].

Fixes:

	$ iamroot-shell -c "alpine-make-rootfs alpine-3.16-rootfs --keys-dir /usr/share/apk/keys/x86_64 --mirror-uri http://nl.alpinelinux.org/alpine --branch 3.16"

	> Installing system
	fetch http://nl.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
	fetch http://nl.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
	(1/7) Installing alpine-baselayout-data (3.2.0-r20)
	ERROR: alpine-baselayout-data-3.2.0-r20: package mentioned in index not found (try 'apk update')
	(2/7) Installing musl (1.2.3-r0)
	(3/7) Installing busybox (1.35.0-r8)
	ERROR: busybox-1.35.0-r8: package mentioned in index not found (try 'apk update')
	(4/7) Installing alpine-baselayout (3.2.0-r20)
	ERROR: alpine-baselayout-3.2.0-r20: package mentioned in index not found (try 'apk update')
	(5/7) Installing busybox-suid (1.35.0-r8)
	ERROR: busybox-suid-1.35.0-r8: package mentioned in index not found (try 'apk update')
	(6/7) Installing scanelf (1.3.3-r0)
	ERROR: scanelf-1.3.3-r0: package mentioned in index not found (try 'apk update')
	(7/7) Installing musl-utils (1.2.3-r0)
	5 errors; 0 MiB in 2 packages

[1]: https://github.com/alpinelinux/alpine-make-rootfs/commit/f60713cad39fef1a22fc11c2a57d23f1150f17c7
[2]: https://nl.alpinelinux.org/alpine/v3.16/main/x86_64/musl-utils-1.2.3-r0.apk
[3]: https://nl.alpinelinux.org/alpine/v3.16/main/x86_64/
[4]: https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/musl-utils-1.2.3-r0.apk
[5]: https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/scanelf-1.3.4-r0.apk
[6]: https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/