makefile: fix aarch64-arch-rootfs target
This fixes commit ecbade462c3c7f2a6a805bb8af25e8ccc2196bc2.

The Arch Linux ARM distro does not ship lib64 symlinks.

Fixes:

	ERROR: ld.so: object '/home/gportay/src/iamroot/aarch64-arch-rootfs/usr/lib64/libc.so.6' from --preload cannot be preloaded (cannot open shared object file): ignored.
	ERROR: ld.so: object '/home/gportay/src/iamroot/aarch64-arch-rootfs/usr/lib64/libdl.so.2' from --preload cannot be preloaded (cannot open shared object file): ignored.