Remove macros _getenv, _setenv _putenv and _unsetenv
This fixes commit fcf6940a210ce48f20e3e2ff7b156a85ce423de4

Fixes:

	$ make test
	(...)
	/usr/bin/ld: /tmp/ccSidDl6.o: in function `main':
	test-path_setenv.c:(.text+0xaf): undefined reference to `_getenv'
	/usr/bin/ld: test-path_setenv.c:(.text+0xf0): undefined reference to `_getenv'
	collect2: error: ld returned 1 exit status