Re-apply "execve: run exec.sh using chroot'ed shell"
This re-applies commit ceea1f566668106e21a0e36fccfb477da42fef8d.

Fixes:

	var/cache/misc/busybox-1.34.1-r4.trigger: line 20: /bin/bbsuid: not found

This adds three additional changes to execve.c and exec.sh.

In execve.c:

 * the function execve() runs the exec.sh shell script directly instead
   of running it through its interpreter (/bin/bash); there is no bash
   applet in busybox.

In exec.sh:

 * the hashbang is downgraded to simple /bin/sh as the busybox world
   does not support for bash.
 * the intercepted bbsuid command is now unsetting the environment
   (LD_LIBRARY_PATH, IAMROOT_ROOT) as for any other intercepted
   commands.

The alpine rootfs now builds correctly with theses three additional
changes:

	$ bash iamroot-shell -c "alpine-make-rootfs alpine-edge-rootfs --mirror-uri http://nl.alpinelinux.org/alpine --branch edge"

	> Installing system
	fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
	fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
	(1/6) Installing musl (1.2.2-r7)
	(2/6) Installing busybox (1.34.1-r5)
	Executing busybox-1.34.1-r5.post-install
	(3/6) Installing alpine-baselayout (3.2.0-r18)
	Executing alpine-baselayout-3.2.0-r18.pre-install
	Executing alpine-baselayout-3.2.0-r18.post-install
	(4/6) Installing busybox-suid (1.34.1-r5)
	(5/6) Installing scanelf (1.3.3-r0)
	(6/6) Installing musl-utils (1.2.2-r7)
	Executing busybox-1.34.1-r5.trigger
	OK: 2 MiB in 6 packages
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
	tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'

	> Cleaning-up rootfs

Fixes:

	$ bash iamroot-shell -c "pacstrap arch-rootfs"
	(...)
	( 8/10) Arming ConditionNeedsUpdate...
	(...)
	/usr/share/libalpm/scripts/systemd-hook: line 31: /bin/touch: Operation not supported
	error: command failed to execute correctly

	$ bash iamroot-shell -c "dnf --releasever 34 --assumeyes --installroot /home/gportay/src/iamroot/fedora-34-rootfs group install minimal-environment"
	(...)
	  Running scriptlet: glibc-2.33-5.fc34.x86_64                            27/306
	/usr/sbin/ldconfig: error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument
	(...)
	  Running scriptlet: rootfiles-8.1-29.fc34.noarch                       306/306
	/sbin/ldconfig: error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument
	warning: %transfiletriggerin(glibc-common-2.33-5.fc34.x86_64) scriptlet failed, exit status 127

	Error in <unknown> scriptlet in rpm package rootfiles
	(...)

Note: However, it raises the following error:

	$ bash iamroot-shell -c "dnf --releasever 34 --assumeyes --installroot /home/gportay/src/iamroot/fedora-34-rootfs group install minimal-environment"
	(...)
	  Running scriptlet: glibc-2.33-5.fc34.x86_64                            27/306
	getinterp: No such file or directory

	error: lua script failed: [string "%post(glibc-2.33-5.fc34.x86_64)"]:12: /usr/sbin/ldconfig: Invalid argument
	error: No exec() called after fork() in lua scriptlet