Steal reallocarr() from NetBSD
The build issue below is raised if -O2; it was revealed since the commit
f6db491554333ec4ee0733490c5adc7f03c5eb0f:

	cc -g -Werror -O2 -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=23 -DPREFIX=/usr/local  -c -o fts.o /home/gportay/src/iamroot/fts.c
	In function ‘reallocarr’,
	    inlined from ‘fts_sort’ at /home/gportay/src/iamroot/fts.c:1200:11:
	/home/gportay/src/iamroot/fts.c:26:13: error: ‘reallocarray’ called on pointer ‘sp’ with nonzero offset 16 [-Werror=free-nonheap-object]
	   26 |         p = reallocarray(ptr, m, n);
	      |             ^~~~~~~~~~~~~~~~~~~~~~~
	cc1: all warnings being treated as errors

Fixes:

	Regenerating man db...
	realloc(): invalid pointer
	Aborted (core dumped)

See:

	GNU gdb (GDB) 15.2
	Copyright (C) 2024 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.
	Type "show copying" and "show warranty" for details.
	This GDB was configured as "x86_64-pc-linux-gnu".
	Type "show configuration" for configuration details.
	For bug reporting instructions, please see:
	<https://www.gnu.org/software/gdb/bugs/>.
	Find the GDB manual and other documentation resources online at:
	    <http://www.gnu.org/software/gdb/documentation/>.

	For help, type "help".
	Type "apropos word" to search for commands related to "word"...
	Reading symbols from /home/gportay/src/iamroot/x86_64-voidlinux-rootfs/usr/lib/ld-linux-x86-64.so.2...

	warning: core file may not match specified executable file.
	[New LWP 1347107]

	This GDB supports auto-downloading debuginfo from the following URLs:
	  <https://debuginfod.archlinux.org>
	Enable debuginfod for this session? (y or [n]) y
	Debuginfod has been enabled.
	To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.

	warning: File "/home/gportay/src/iamroot/x86_64-voidlinux-rootfs/usr/lib/libthread_db.so.1" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
	To enable execution of this file add
		add-auto-load-safe-path /home/gportay/src/iamroot/x86_64-voidlinux-rootfs/usr/lib/libthread_db.so.1
	line to your configuration file "/home/gportay/.config/gdb/gdbinit".
	To completely disable this security protection add
		set auto-load safe-path /
	line to your configuration file "/home/gportay/.config/gdb/gdbinit".
	For more information about this security protection see the
	"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
		info "(gdb)Auto-loading safe path"

	warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
	Core was generated by `/home/gportay/src/iamroot/x86_64-voidlinux-rootfs/usr/lib/ld-linux-x86-64.so.2'.
	Program terminated with signal SIGABRT, Aborted.
	Download failed: Invalid argument.  Continuing without source file ./nptl/./nptl/pthread_kill.c.
	#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44

	warning: 44	./nptl/pthread_kill.c: No such file or directory
	(gdb) bt
	#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
	#1  0x00007bd290f6f68f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
	#2  0x00007bd290f20822 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
	#3  0x00007bd290f094af in __GI_abort () at ./stdlib/abort.c:79
	#4  0x00007bd290f0a357 in __libc_message_impl (fmt=fmt@entry=warning: BFD: reopening /home/gportay/src/iamroot/x86_64-voidlinux-rootfs/usr/lib/libc.so.6: No such file or directory
	0x7bd2910802f3 "") at ../sysdeps/posix/libc_fatal.c:132
	#5  0x00007bd290f790e7 in malloc_printerr (str=str@entry=0x7bd29107e180 "") at ./malloc/malloc.c:5772
	#6  0x00007bd290f7e09c in __GI___libc_realloc (oldmem=oldmem@entry=0x55556e902460, bytes=bytes@entry=384) at ./malloc/malloc.c:3466
	#7  0x00007bd290f7f510 in __GI___libc_reallocarray (optr=optr@entry=0x55556e902460, nmemb=nmemb@entry=48, elem_size=elem_size@entry=8) at ./malloc/reallocarray.c:32
	#8  0x00007bd2910fab58 in reallocarr (ptr=<optimized out>, m=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, n=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
	    at /home/gportay/src/iamroot/fts.c:26
	#9  0x00007bd2910fac2f in fts_sort (sp=<error reading variable: DW_FORM_addr_index used without .debug_addr section [in module /home/gportay/src/iamroot/x86_64/libiamroot-linux-x86-64.so.2]>,
	    head=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, nitems=<optimized out>) at /home/gportay/src/iamroot/fts.c:1200
	#10 0x00007bd2910fb137 in fts_build (sp=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, type=<optimized out>) at /home/gportay/src/iamroot/fts.c:1097
	#11 0x00007bd2910fb7ad in _fts_read (sp=<optimized out>) at /home/gportay/src/iamroot/fts.c:603
	#12 0x00007bd2910fbcae in fts_read (sp=<optimized out>) at /home/gportay/src/iamroot/fts.c:1450
	warning: BFD: reopening /home/gportay/src/iamroot/x86_64-voidlinux-rootfs/lib64/libdl.so.2: No such file or directory
	warning: Can't read data for section '.eh_frame' in file '/home/gportay/src/iamroot/x86_64-voidlinux-rootfs/lib64/libdl.so.2'
	warning: BFD: reopening /home/gportay/src/iamroot/x86_64-voidlinux-rootfs/lib64/libpthread.so.0: No such file or directory
	warning: Can't read data for section '.eh_frame' in file '/home/gportay/src/iamroot/x86_64-voidlinux-rootfs/lib64/libpthread.so.0'
	warning: BFD: reopening /home/gportay/src/iamroot/x86_64-voidlinux-rootfs/usr/bin/makewhatis: No such file or directory
	#13 0x00007bd291157138 in ?? ()
	#14 0x00007bd2911a9100 in ?? ()
	#15 0x0000000000000000 in ?? ()

See also 48411cfb4095f6df279ad5748ac9cae0b4542de8.