mk{,d}tmep: fix the out-of root directory creation
This fixes commit 1e64cbcf6f37af0c5daa322434ed26b9a681b63e.

This fixes the creation of temporary files or directories made out-of
the root directory as the given path is not resolved since the commit
1e64cbcf6f37af0c5daa322434ed26b9a681b63e.

Fixes:

	$ pacman -S sway
	(...)
	:: Processing package changes...
	error: could not change directory to /tmp/alpm_tkEt8R (No such file or directory)
	warning: could not remove /tmp/alpm_tkEt8R/.INSTALL
	warning: could not remove tmpdir /tmp/alpm_tkEt8R