Add __openat_2() again
This reverts commit aa2366b0032610d3b5ad349e9d82ec8e7b49c09b.

Fixes:

	$ makepkg
	(...)
	In file included from /home/gportay/src/iamroot/support/src/iamroot-git/openat.c:22:
	/home/gportay/src/iamroot/support/src/iamroot-git/openat.c:85:20: error: conflicting types for ‘__openat_2’; have ‘int(int,  const char *, int, ...)’
	   85 | weak_alias(openat, __openat_2);
	      |                    ^~~~~~~~~~
	/home/gportay/src/iamroot/support/src/iamroot-git/iamroot.h:20:30: note: in definition of macro ‘weak_alias’
	   20 |         extern __typeof(old) new __attribute__((__weak__, __alias__(#old)))
	      |                              ^~~
	In file included from /usr/include/fcntl.h:342,
	                 from /home/gportay/src/iamroot/support/src/iamroot-git/openat.c:20:
	/usr/include/bits/fcntl2.h:98:12: note: previous declaration of ‘__openat_2’ with type ‘int(int,  const char *, int)’
	   98 | extern int __openat_2 (int __fd, const char *__path, int __oflag)
	      |            ^~~~~~~~~~
	/home/gportay/src/iamroot/support/src/iamroot-git/openat.c:87:20: error: conflicting types for ‘__openat64_2’; have ‘int(int,  const char *, int, ...)’
	   87 | weak_alias(openat, __openat64_2);
	      |                    ^~~~~~~~~~~~
	/home/gportay/src/iamroot/support/src/iamroot-git/iamroot.h:20:30: note: in definition of macro ‘weak_alias’
	   20 |         extern __typeof(old) new __attribute__((__weak__, __alias__(#old)))
	      |                              ^~~
	/usr/include/bits/fcntl2.h:140:12: note: previous declaration of ‘__openat64_2’ with type ‘int(int,  const char *, int)’
	  140 | extern int __openat64_2 (int __fd, const char *__path, int __oflag)
	      |            ^~~~~~~~~~~~
	make[1]: *** [<builtin>: openat.o] Error 1
	make: *** [makefile:537: output-i686-linux/libiamroot.so] Error 2