tests: ish: disable test breaking CI
The test for option -i breaks CI.

The FreeBSD-vm workflow hangs forever:

	Running ish: test option -i specifies the shell is interactive...
	(...)
	Error: The operation was canceled.

While the NetBSD-vm and OpenBSD-vm workflows fails simply:

	Running ish: test option -i specifies the shell is interactive...
	ish: test option -i specifies the shell is interactive: [KO]
	(...)
	Test report:
	23 test(s) succeed!
	ish: test option -i specifies the shell is interactive at line 207 has failed!
	Error: 1 test(s) failed!

This disables the test for option -i.