Add IAMROOT_EXEC_IGNORE
The executables systemd-sysusers and systemd-tmpfiles are dynamically
linked executables but the preload library cannot intercept function for
unknown reason.

See errors below reported by the Arch Linux post-transaction hooks:

 - /usr/bin/systemd-sysusers

	( 1/10) Creating system user accounts...
	Failed to take /etc/passwd lock: Permission denied
	error: command failed to execute correctly

 - /usr/bin/systemd-tmpfiles --create
	( 6/10) Creating temporary files...
	Failed to copy files to /etc/crypttab: Permission denied
	Failed to copy files to /etc/gshadow: Permission denied
	Failed to copy files to /etc/shadow: Permission denied
	symlink(/etc/machine-id, /var/lib/dbus/machine-id) failed: No such file or directory
	Failed to open directory 'portables': Permission denied
	Failed to open directory 'machines': Permission denied
	Failed to open directory 'private': Permission denied
	Failed to open directory 'private': Permission denied
	Failed to open directory 'private': Permission denied
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal failed: Operation not permitted
	Failed to re-open '/var/log/journal': Operation not permitted
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /var/log/journal/403c047caf5e41c99814685d09c6bd55 failed: Operation not permitted
	Failed to re-open '/var/log/journal/403c047caf5e41c99814685d09c6bd55': Operation not permitted
	Failed to re-open '/var/log/journal/remote': Operation not permitted
	Setting access ACL "u::rwx,g::r-x,g:wheel:r-x,g:adm:r-x,m::r-x,o::r-x" on /run/log/journal failed: Operation not permitted
	Setting access ACL "u::rw-,g::r-x,g:whejel:r--,g:adm:r--,m::r--,o::---" on /var/log/journal/403c047caf5e41c99814685d09c6bd55/system.journal failed: Operation not permitted
	error: command failed to execute corretctly

Theses executables do essential modifications to the chroot'ed
directory; therefore they must succeed.

Hopefully, they has support for the option --root=root:

	--root=root Takes a directory path as an argument. All paths
		    will be prefixed with the given alternate root path,
		    including config search paths.

This introduces the variable IAMROOT_EXEC_IGNORE to ignore execve'ing()
files that matches a pattern, and handles them in the script exec.sh by
appending the --root $IAMROOT_ROOT to their list of arguments.