chroot: use next_getcwd()
The path in the if statement is handling relative paths and prepend both
root and cwd directory to the given path.

This results in a segmentation fault if the process is not in a chroot()
environment (i.e. the funciton getrootdir() returns "/").

This calls the getcwd() instead that returns the actual path (including
the chroot directory.

Important: This does not fix the segmentation fault below.

Fixes:

	$ make --silent x86_64-opensuse-tumbleweed-rootfs
	Adding repository 'openSUSE-Tumbleweed-Oss' [...done]
	Warning: GPG checking is disabled in configuration of repository 'openSUSE-Tumbleweed-Oss'. Integrity and origin of packages cannot be verified.
	Repository 'openSUSE-Tumbleweed-Oss' successfully added

	URI         : http://download.opensuse.org/tumbleweed/repo/oss/
	Enabled     : Yes
	GPG Check   : No
	Autorefresh : Yes
	Priority    : 99 (default priority)

	Repository priorities are without effect. All enabled repositories share the same priority.
	Retrieving repository 'openSUSE-Tumbleweed-Oss' metadata [.done]
	Building repository 'openSUSE-Tumbleweed-Oss' cache [....done]
	Loading repository data...
	Reading installed packages...
	Resolving package dependencies...

	The following 29 recommended packages were automatically selected:
	  aaa_base-extras augeas-lenses ca-certificates-mozilla cpio-mt cracklib-dict-full crypto-policies-scripts dbus-1-daemon dirmngr dump-rmt glibc-extra iproute2 iputils libldap-data libpcre2-8-0 login_defs logrotate lsof ncurses-utils netcfg pam-manpages pam_pwquality publicsuffix python310 python310-curses python310-dbm python310-pip terminfo-screen timezone zypper-log

	The following 198 NEW packages are going to be installed:
	  aaa_base aaa_base-extras alts augeas-lenses bash bash-sh boost-license1_81_0 branding-openSUSE busybox busybox-gawk busybox-grep busybox-sed busybox-xz ca-certificates ca-certificates-mozilla chkstat compat-usrmerge-tools coreutils cpio cpio-mt cracklib cracklib-dict-full crypto-policies crypto-policies-scripts dbus-1 dbus-1-common dbus-1-daemon dbus-1-tools diffutils dirmngr dump-rmt file-magic filesystem fillup findutils glibc glibc-extra gpg2 iproute2 iputils kbd kbd-legacy krb5 libacl1 libalternatives1 libapparmor1 libassuan0 libattr1 libaudit1 libaugeas0 libblkid1 libboost_thread1_81_0 libboost_thread1_81_0-x86-64-v3 libbpf1 libbrotlicommon1 libbrotlicommon1-x86-64-v3 libbrotlidec1 libbrotlidec1-x86-64-v3 libbz2-1 libbz2-1-x86-64-v3 libcap2 libcap-ng0 libcom_err2 libcrack2 libcrypt1 libcurl4 libdbus-1-3 libeconf0 libelf1 libexpat1 libfa1 libfdisk1 libffi8 libgcc_s1 libgcrypt20 libgcrypt20-x86-64-v3 libgdbm6 libgdbm_compat4 libglib-2_0-0 libgmp10 libgnutls30 libgpg-error0 libgpgme11 libhogweed6 libhogweed6-x86-64-v3 libidn2-0 libip4tc2 libjitterentropy3 libkeyutils1 libkmod2 libksba8 libldap2 libldap-data liblua5_4-5 liblz4-1 liblz4-1-x86-64-v3 liblzma5 liblzma5-x86-64-v3 libmagic1 libmnl0 libmount1 libmpdec3 libncurses6 libnettle8 libnettle8-x86-64-v3 libnghttp2-14 libnpth0 libnss_usrfiles2 libopenssl3 libopenssl3-x86-64-v3 libp11-kit0 libpcre2-8-0 libpkgconf3 libpopt0 libproc2-0 libprotobuf-lite3_21_12 libproxy1 libpsl5 libpwquality1 libpython3_10-1_0 libreadline8 libsasl2-3 libseccomp2 libselinux1 libsepol2 libsigc-2_0-0 libsmartcols1 libsolv-tools libsqlite3-0 libsqlite3-0-x86-64-v3 libssh4 libssh-config libstdc++6 libsystemd0 libtasn1-6 libudev1 libunistring5 libusb-1_0-0 libutempter0 libuuid1 libverto1 libxml2-2 libxtables12 libyaml-cpp0_7 libzck1 libz-ng-compat1 libzstd1 libzstd1-x86-64-v3 libzypp login_defs logrotate lsof ncurses-utils netcfg openSUSE-build-key openSUSE-release openSUSE-release-appliance-custom p11-kit p11-kit-tools pam pam-config pam-manpages pam_pwquality patterns-base-minimal_base patterns-glibc-hwcaps-x86_64_v3 permissions permissions-config pinentry pkgconf pkgconf-m4 pkgconf-pkg-config procps4 publicsuffix python310 python310-base python310-curses python310-dbm python310-pip python310-setuptools rpm rpm-config-SUSE shared-python-startup systemd systemd-default-settings systemd-default-settings-branding-openSUSE systemd-presets-branding-openSUSE systemd-presets-common-SUSE system-group-hardware system-user-root sysuser-shadow terminfo-base terminfo-screen timezone update-alternatives util-linux zypper zypper-log zypper-needs-restarting

	198 new packages to install.
	Overall download size: 68.4 MiB. Already cached: 0 B. After the operation, additional 216.6 MiB will be used.
	Continue? [y/n/v/...? shows all options] (y): y

	Checking for file conflicts: [...done]
	Warning: 198 packages had to be excluded from file conflicts check because they are not yet downloaded.

	    Note: Checking for file conflicts requires not installed packages to be downloaded in advance in
	    order to access their file lists. See option '--download-in-advance / --dry-run --download-only'
	    in the zypper manual page for details.

	Retrieving package boost-license1_81_0-1.81.0-2.2.noarch (1/198),  14.5 KiB (  1.3 KiB unpacked)
	Retrieving: boost-license1_81_0-1.81.0-2.2.noarch.rpm [done]
	(  1/198) Installing: boost-license1_81_0-1.81.0-2.2.noarch [.
	warning: /home/gportay/src/iamroot/x86_64-opensuse-tumbleweed-rootfs/var/cache/zypp/packages/repo-oss/noarch/boost-license1_81_0-1.81.0-2.2.noarch.rpm: Header V3 RSA/SHA512 Signature, key ID 29b700a4: NOKEY
		.
	warning: Unable to get systemd shutdown inhibition lock: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
	error]
	Installation of boost-license1_81_0-1.81.0-2.2.noarch failed:
	Error: Subprocess failed. Error: RPM failed: Command was killed by signal 11 (Segmentation fault).
	Abort, retry, ignore? [a/r/i] (a): a
	Problem occurred during or after installation or removal of packages:
	Installation has been aborted as directed.
	Please see the above error message for a hint.
	make[1]: *** [makefile:679: x86_64-opensuse-tumbleweed-rootfs/etc/machine-id] Error 8
	make: *** [makefile:678: x86_64-opensuse-tumbleweed-rootfs.log] Error 2

See:

	$ coredumpctl debug
	           PID: 1721800 (rpm)
	           UID: 1000 (gportay)
	           GID: 1000 (gportay)
	        Signal: 11 (SEGV)
	     Timestamp: Sun 2023-03-26 19:22:52 CEST (1min 14s ago)
	  Command Line: rpm --root /home/gportay/src/iamroot/x86_64-opensuse-tumbleweed-rootfs --dbpath /var/lib/rpm -U --percent --noglob --force --nodeps -- /home/gportay/src/iamroot/x86_64-opensuse-tumbleweed-rootfs/var/cache/zypp/packages/repo-oss/noarch/boost-license1_81_0-1.81.0-2.2.noarch.rpm
	    Executable: /usr/bin/rpm
	 Control Group: /user.slice/user-1000.slice/session-1.scope
	          Unit: session-1.scope
	         Slice: user-1000.slice
	       Session: 1
	     Owner UID: 1000 (gportay)
	       Boot ID: 2aa64ec658e848d08021b4eb60a98a12
	    Machine ID: d0f90f2823f7457e8c9d36822208c75f
	      Hostname: archlinux
	       Storage: /var/lib/systemd/coredump/core.rpm.1000.2aa64ec658e848d08021b4eb60a98a12.1721800.1679851372000000.zst (present)
	  Size on Disk: 202.2K
	       Message: Process 1721800 (rpm) of user 1000 dumped core.

	                Stack trace of thread 1721800:
	                #0  0x00007f8a0f008f05 rpmtsRun (librpm.so.9 + 0x49f05)
	                ELF object binary architecture: AMD x86-64

	GNU gdb (GDB) 13.1
	Copyright (C) 2023 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.
	Type "show copying" and "show warranty" for details.
	This GDB was configured as "x86_64-pc-linux-gnu".
	Type "show configuration" for configuration details.
	For bug reporting instructions, please see:
	<https://www.gnu.org/software/gdb/bugs/>.
	Find the GDB manual and other documentation resources online at:
	    <http://www.gnu.org/software/gdb/documentation/>.

	For help, type "help".
	Type "apropos word" to search for commands related to "word"...
	Reading symbols from /usr/bin/rpm...

	This GDB supports auto-downloading debuginfo from the following URLs:
	  <https://debuginfod.archlinux.org>
	Enable debuginfod for this session? (y or [n]) y
	Debuginfod has been enabled.
	To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
	Reading symbols from /home/gportay/.cache/debuginfod_client/954595a88b00b1cc49540686dc414f864dc48f8c/debuginfo...
	[New LWP 1721800]
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/usr/lib/libthread_db.so.1".
	Core was generated by `rpm --root /home/gportay/src/iamroot/x86_64-opensuse-tumbleweed-rootfs --dbpath'.
	Program terminated with signal SIGSEGV, Segmentation fault.
	#0  0x00007f8a0f008f05 in rpmtsPrepare (ts=<optimized out>) at /usr/src/debug/rpm-tools/rpm-4.18.1/lib/transaction.c:1601
	1601	   rpmtsNotify(ts, NULL, RPMCALLBACK_TRANS_STOP, 6, tsmem->orderCount);
	(gdb) bt
	#0  0x00007f8a0f008f05 in rpmtsPrepare (ts=<optimized out>) at /usr/src/debug/rpm-tools/rpm-4.18.1/lib/transaction.c:1601
	#1  rpmtsRun (ts=<optimized out>, okProbs=<optimized out>, ignoreSet=<optimized out>)
	    at /usr/src/debug/rpm-tools/rpm-4.18.1/lib/transaction.c:1825
	Backtrace stopped: Cannot access memory at address 0x4800060e