dso: fix maybe-uninitialized warning
Fixes:

	$ make
	(...)
	cc -g -Werror -Wno-deprecated-declarations -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=14 -DPREFIX=/usr/local  -c -o dso.o /home/gportay/src/iamroot/dso.c
	/home/gportay/src/iamroot/dso.c: In function ‘__ldso’:
	/home/gportay/src/iamroot/dso.c:2266:31: error: ‘inhibit_rpath’ may be used uninitialized [-Werror=maybe-uninitialized]
	 2266 |         if (has_inhibit_rpath && inhibit_rpath)
	      |                               ^~
	/home/gportay/src/iamroot/dso.c:2126:23: note: ‘inhibit_rpath’ was declared here
	 2126 |         char *argv0, *inhibit_rpath, *ld_library_path, *ld_preload;
	      |                       ^~~~~~~~~~~~~
	cc1: all warnings being treated as errors