Fix "path_resolution: add NOWALKALONG private flag"
This fixes commit 467cdb7a2a1e3c06b0f73e04860db26eedc7bd06.

Fixes (FreeBSD):

	[freebox@freebsd ~/src/iamroot]$ make
	(...)
	cc -Wl,-rpath,/usr/local/lib/iamroot  __fstat50.o __fxstat.o __fxstatat.o dlopen.o dso.o env.o execve.o execvpe.o extattr_delete_link.o extattr_get_fd.o extattr_get_link.o extattr_set_fd.o extattr_set_link.o faccessat.o fgetxattr.o fstat.o fstatat.o getcwd.o getxattr.o iamroot.o interpreter-script.o jimregexp.o ld.o ldso-cache.o lgetxattr.o lremovexattr.o lsetxattr.o open.o path_resolution.o readlinkat.o realpath.o scandir.o   -o ld-iamroot.so
	ld: error: undefined symbol: next_extattr_get_file
	>>> referenced by path_resolution.c
	>>>               path_resolution.o:(__realpathat)
	cc: error: linker command failed with exit code 1 (use -v to see invocation)

Fixes (NetBSD):

	-bash-5.2$ make
	(...)
	cc -Wl,-rpath,/usr/local/lib/iamroot  __fstat50.o __fxstat.o __fxstatat.o dlopen.o dso.o env.o execve.o execvpe.o extattr_delete_link.o extattr_get_fd.o extattr_get_link.o extattr_set_fd.o extattr_set_link.o faccessat.o fgetxattr.o fstat.o fstatat.o getcwd.o getxattr.o iamroot.o interpreter-script.o jimregexp.o ld.o ldso-cache.o lgetxattr.o lremovexattr.o lsetxattr.o open.o path_resolution.o readlinkat.o realpath.o scandir.o   -o ld-iamroot.so
	ld: path_resolution.o: in function `__realpathat':
	path_resolution.c:(.text+0x3b0): undefined reference to `next_extattr_get_file'
	ld: path_resolution.c:(.text+0x3b0): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `next_extattr_get_file'