Fix "Save opened fd in the environment"
OpenBSD raises the errors below:

Fixes:

	$ make
	(...)
	cc -Werror -DNVERBOSE -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=11 -DPREFIX=/usr/local  -c -o path_resolution.o /home/freebox/src/iamroot/path_resolution.c
	/home/freebox/src/iamroot/path_resolution.c:96:7: error: unused variable 'buf' [-Werror,-Wunused-variable]
	        char buf[NAME_MAX];
	             ^
	1 error generated.

This fixes commit 0bc95a0264d98b4942c09a1d354ed65e77905170.