fts{,64}: fix free-nonheap-object warning
Fixes:

	$ make
	(...)
	cc -g -Werror -Wno-deprecated-declarations -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=14 -DPREFIX=/usr/local  -c -o fts.o /home/gportay/src/iamroot/fts.c
	In function ‘reallocarr’,
	    inlined from ‘fts_sort’ at /home/gportay/src/iamroot/fts.c:1183:11:
	/home/gportay/src/iamroot/fts.c:19:13: error: ‘reallocarray’ called on pointer ‘sp’ with nonzero offset 16 [-Werror=free-nonheap-object]
	   19 |         p = reallocarray(ptr, nmemb, size);
	      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	cc1: all warnings being treated as errors