makefile: remove edge from alpine{-log,-support} targets
alpine edge x86_64 is broken since musl 1.2.3.

The postinstall scripts fail to run because /bin/sh raises a
segmentation fault.

	$ bash iamroot-shell -c "alpine-make-rootfs alpine-edge-rootfs --keys-dir /usr/share/apk/keys/x86_64 --mirror-uri http://nl.alpinelinux.org/alpine --branch edge"

	> Installing system
	fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
	fetch http://nl.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
	(1/7) Installing alpine-baselayout-data (3.2.0-r20)
	(2/7) Installing musl (1.2.3-r0)
	(3/7) Installing busybox (1.35.0-r8)
	Executing busybox-1.35.0-r8.post-install
	ERROR: busybox-1.35.0-r8.post-install: script exited with error 0
	(4/7) Installing alpine-baselayout (3.2.0-r20)
	Executing alpine-baselayout-3.2.0-r20.pre-install
	ERROR: alpine-baselayout-3.2.0-r20.pre-install: script exited with error 0
	Executing alpine-baselayout-3.2.0-r20.post-install
	ERROR: alpine-baselayout-3.2.0-r20.post-install: script exited with error 0
	(5/7) Installing busybox-suid (1.35.0-r8)
	(6/7) Installing scanelf (1.3.3-r0)
	(7/7) Installing musl-utils (1.2.3-r0)
	Executing busybox-1.35.0-r8.trigger
	ERROR: busybox-1.35.0-r8.trigger: script exited with error 0

	$ bash iamroot-shell
	# chroot alpine-edge-rootfs /bin/sh
	[iamroot][root@archlinux iamroot]# chroot alpine-edge-rootfs/ /bin/sh
	Segmentation fault (core dumped)

	[gportay@archlinux iamroot]$ coredumpctl info | cat
	           PID: 616805 (ld-musl-x86_64.)
	           UID: 1000 (gportay)
	           GID: 1000 (gportay)
	        Signal: 11 (SEGV)
	     Timestamp: Tue 2022-04-12 00:35:41 CEST (10min ago)
	  Command Line: /home/gportay/src/iamroot/alpine-edge-rootfs/lib/ld-musl-x86_64.so.1 --preload /home/gportay/src/iamroot/x86_64/libiamroot-musl-x86_64.so.1:/home/gportay/src/iamroot/alpine-edge-rootfs/usr/lib64/libc.so.6:/home/gportay/src/iamroot/alpine-edge-rootfs/usr/lib64/libdl.so.2 --library-path /home/gportay/src/iamroot/alpine-edge-rootfs/usr/lib:/home/gportay/src/iamroot/alpine-edge-rootfs/lib --argv0 /bin/sh /home/gportay/src/iamroot/alpine-edge-rootfs/bin/busybox
	    Executable: /home/gportay/src/iamroot/alpine-edge-rootfs/lib/ld-musl-x86_64.so.1
	 Control Group: /user.slice/user-1000.slice/session-2.scope
	          Unit: session-2.scope
	         Slice: user-1000.slice
	       Session: 2
	     Owner UID: 1000 (gportay)
	       Boot ID: 20aafda5b45b438c89a1b05ada892200
	    Machine ID: 403c047caf5e41c99814685d09c6bd55
	      Hostname: archlinux
	       Storage: /var/lib/systemd/coredump/core.ld-musl-x86_64\x2e.1000.20aafda5b45b438c89a1b05ada892200.616805.1649716541000000.zst (present)
	     Disk Size: 20.2K
	       Message: Process 616805 (ld-musl-x86_64.) of user 1000 dumped core.

	                Module /home/gportay/src/iamroot/x86_64/libiamroot-musl-x86_64.so.1 without build-id.
	                Module /home/gportay/src/iamroot/alpine-edge-rootfs/bin/busybox without build-id.
	                Module /home/gportay/src/iamroot/alpine-edge-rootfs/lib/ld-musl-x86_64.so.1 without build-id.
	                Module linux-vdso.so.1 with build-id ae8518a0710c2679844504efb751b01abf13cef5
	                Stack trace of thread 616805:
	                #0  0x00007f03ce64c6b9 n/a (/home/gportay/src/iamroot/alpine-edge-rootfs/lib/ld-musl-x86_64.so.1 + 0x516b9)
	                #1  0x00007f03ce577139 n/a (/home/gportay/src/iamroot/alpine-edge-rootfs/bin/busybox + 0x49139)
	                ELF object binary architecture: AMD x86-64

	(gdb) r alpine-edge-rootfs/ /bin/sh
	Starting program: /usr/bin/chroot alpine-edge-rootfs/ /bin/sh
	(...)
	Program received signal SIGSEGV, Segmentation fault.

	(gdb) symbol-file /usr/lib/debug/lib/ld-musl-x86_64.so.1.debug
	Reading symbols from /usr/lib/debug/lib/ld-musl-x86_64.so.1.debug...
	(gdb) bt
	#0  memcpy () at src/string/x86_64/memcpy.s:18
	#1  0x00007ffff7e7c811 in ?? ()
	#2  0x0000000000000000 in ?? ()

However, bash works!

	# chroot alpine-edge-rootfs /bin/bash
	[iamroot][root@archlinux iamroot]# chroot alpine-edge-rootfs/ /bin/bash
	bash-5.1#