support: PKGBUILD: fix missing lib32-glibc build dependency
Fixes:

	==> Starting build()...
	mkdir output-i686-linux
	make -f /home/gportay/src/iamroot/support/src/iamroot-git/Makefile -C output-i686-linux libiamroot.so VPATH=/home/gportay/src/iamroot/support/src/iamroot-git
	cc -m32 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -fno-stack-protector -fPIC -Wall -Wextra -D_GNU_SOURCE -DVERSION=r1011.a4f354c  -c -o __abort.o /home/gportay/src/iamroot/support/src/iamroot-git/__abort.c
	In file included from /usr/include/features.h:514,
	                 from /usr/include/signal.h:25,
	                 from /home/gportay/src/iamroot/support/src/iamroot-git/__abort.c:7:
	/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory
	    7 | # include <gnu/stubs-32.h>
	      |           ^~~~~~~~~~~~~~~~
	compilation terminated.