Remove mktemp() and mkdtemp()
These functions are not correcly implemented.

In particular, the function mkdtemp() causes the issue below:

	(---/---) installing foo
	chdir: No such file or directory
	error: could not change directory to /absolute/path/to/arch-rootfs/tmp/alpm_XXXXXX (No such file or directory)
	warning: could not remove /absolute/path/to/arch-rootfs/tmp/alpm_XXXXXX/.INSTALL
	warning: could not remove tmpdir /absolute/path/to/arch-rootfs/tmp/alpm_XXXXXX