Fix "tests: move mount tests to dedicated script"
The functions mount(), umount() and umount2() do not set the user
extended attribute user.iamroot.path-resolution yet.

This fixes commit 74aa31bed75b9b41051abac798a0040cba01d8df.

Fixes:

	$ make ci
	(...)
	bash tests-libiamroot.so.bash
	Running libiamroot.so: test mount() path resolves virtual filesystem proc(5) using host mountpoint...
	/home/gportay/src/iamroot-for-int/tests/rootfs/proc
	libiamroot.so: test mount() path resolves virtual filesystem proc(5) using host mountpoint: [KO]

	Running libiamroot.so: test umount() path resolves mountpoint...
	/home/gportay/src/iamroot-for-int/tests/rootfs/proc
	libiamroot.so: test umount() path resolves mountpoint: [OK]

	Test report:
	libiamroot.so: test mount() path resolves virtual filesystem proc(5) using host mountpoint at line 182 has failed!
	1 test(s) succeed!
	Error: 1 test(s) failed!