Fix "iamroot-shell: add --preserve-env option" once again
This fixes commit a60fd3fdb32585ca4315e2ea350965d2497fcd07.

Fixes:

	$ make aarch64-alpine-edge-chroot
	bash ish -c "alpine-make-rootfs aarch64-alpine-edge-rootfs --keys-dir /usr/share/apk/keys/aarch64 --mirror-uri http://mirrors.edge.kernel.org/alpine --branch edge "

	> Installing system
	fetch http://mirrors.edge.kernel.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
	fetch http://mirrors.edge.kernel.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
	(1/8) Installing alpine-baselayout-data (3.4.3-r1)
	(2/8) Installing musl (1.2.4-r1)
	(3/8) Installing busybox (1.36.1-r1)
	Executing busybox-1.36.1-r1.post-install
	lib/apk/exec/busybox-1.36.1-r1.post-install: line 4: /bin/busybox: not found
	lib/apk/exec/busybox-1.36.1-r1.post-install: exec: line 5: /bin/busybox: not found
	ERROR: busybox-1.36.1-r1.post-install: script exited with error 127
	(4/8) Installing busybox-binsh (1.36.1-r1)
	(5/8) Installing alpine-baselayout (3.4.3-r1)
	Executing alpine-baselayout-3.4.3-r1.pre-install
	Executing alpine-baselayout-3.4.3-r1.post-install
	chown: invalid group: 'root:shadow'
	chmod: changing permissions of '/etc/shadow': Operation not permitted
	(6/8) Installing busybox-suid (1.36.1-r1)
	(7/8) Installing scanelf (1.3.7-r1)
	(8/8) Installing musl-utils (1.2.4-r1)
	Executing busybox-1.36.1-r1.trigger
	lib/apk/exec/busybox-1.36.1-r1.trigger: line 22: /bin/busybox: not found
	ERROR: busybox-1.36.1-r1.trigger: script exited with error 127
	1 error; 2 MiB in 8 packages
	make: *** [makefile:954: aarch64-alpine-edge-rootfs/bin/busybox] Error 1