execve: fix execve'ing EFAULT
The environment is updated before runnning the exec.sh since the commit
83e212844554214f2274491974e932e0b5fb677a.

The global environ is updated but the actual call to execve still uses
the free'ed environment stored in envp.

This applies and factorizes the fix used for exec'ing the dynamic loader
in the chroot.

Fixes:

	call to execv failed (Bad address)
	error: command failed to execute correctly

And:
	error: lua script failed: [string "%post(glibc-2.34-7.fc35.x86_64)"]:14: assertion failed!
	error: No exec() called after fork() in lua scriptlet